### ISSUE TITLE
No license.filebot.net

### ISSUE THREAD

**Issue by finitelife** [filebot/website#1]
I can understand why it isn't there, but it would be helpful to implement a local mirror of the licensing model for testing. Hopefully there is a way to implement this without revealing sensitive information.

I am currently bypassing licensing in order to test all affected functions, but I'd love to just swap out the verify https address and local/remote keys for a mostly vanilla experience.

**Comment by rednoah** [comment]
Bypassing central licensing is generally discouraged and frowned upon:
https://github.com/filebot/filebot/blob/master/LICENSE.md

(unless you have a really really good reason, such as me meeting my untimely demise and official infrastructure breaking down)

**Comment by finitelife** [comment]
Sorry man, it was/is legit for testing purposes. I have not and will not
share my method. I continue to use the last free release day to day. I
would actually like to test out the online licensing scheme, thus the
query. I will be buying 4.8.5+, but being an expat in Vietnam kinda hampers
my online purchasing options.

**Comment by rednoah** [comment]
No worries then.
